from lib.models.backbones import dla
from lib.models.backbones.dlaup import DLAUp
import numpy as np

def build_backbone_neck(cfg):
    backbone = cfg['backbone']['type']
    backbone_model = getattr(dla, backbone)(pretrained=True, return_levels=True)
    channels = backbone_model.channels  # channels list for feature maps generated by backbone
    # self.first_level = int(np.log2(downsample))
    downsample = cfg['neck']['downsample']
    first_level = int(np.log2(downsample))
    scales = [2 ** i for i in range(len(channels[first_level:]))]
    neck_model = DLAUp(channels[first_level:], scales_list=scales)  # feature fusion [such as DLAup, FPN]

    return backbone_model, neck_model

